### ISSUE TITLE
Usage of quoteTableName() with PostgreSQL tables

### ISSUE THREAD

**Issue by MB34** [delight-im/PHP-DB#11]
From: http://blog.lerner.co.il/quoting-postgresql/

In PostgreSQL are used to create a text string, double quotes are used to name an identifier without changing its case. Single quotes and double quotes in PostgreSQL have completely different jobs, and return completely different data types.  Single quotes return text strings.  Double quotes return (if you can really think of them as “returning” anything) identifiers, but with the case preserved.

Thus, if I were to repeat the above table-creation query, but use double quotes:

    CREATE TABLE "People" (
        id SERIAL NOT NULL,
        email TEXT NOT NULL,
        PRIMARY KEY(id)
    );

I have now created a table in which the table name has not been forced to lowercase, but which has preserved the capital P.  This means that the following query will now fail:

    select * from people;

    ERROR: relation "people" does not exist
    LINE 1: select * from people;
                          ^

This also means that when looking at the table name in PGAdmin it will show the table name as `"People"` not `People` or `people`.

Using the `quoteTableName` function with the default table names, including the new schema causes the 
`Undefined table: 7 ERROR: relation "schema.users_throttling" does not exist`

Since you are not creating the tables with mixed case OR with double quotes around the name in the SQL script, you need to not use the double quotes in any SQL calling those tables, OR reconfigure your create SQL to include the double quotes around the table names. This might also cause issues when adding the schema because `"schema.tablename"` is not the same as `schema."tablename"`.

Do you see the issue here? I commented out the calls to `quoteTableName` and changed 
`$statement = 'UPDATE '.$tableName.' SET '...` to
`$statement = 'UPDATE '.$tableName[0].' SET ' `
to get it working but this needs to be addressed.

**Comment by ocram** [comment]
Thanks!

The table names themselves have always been quoted in this library. But you probably have not experienced this before because you had commented out the calls adding the quotes in order to make your schema-qualified table names work.

Now that we have added support for specifying schemas, we do the same quoting as before, but apply it correctly to both schema and table name. So we don’t do the wrong `"schema.users_throttling"` but the correct `"schema"."users_throttling"`, as far as I can see. And we certainly don’t use single quotes.

The number one goal of this library is security. So I think always quoting schema names and table names is the right thing to do here. It helps protect against SQL injections, and it makes sure there are never conflicts with reserved keywords.

Regarding the actual problem here, no, I actually don’t see what’s the issue. Quoted identifiers retain their case and unquoted identifiers are converted to lowercase. That’s all, right?

So in the table definitions of [our authentication library](https://github.com/delight-im/PHP-Auth), we consistently use lowercase, and we even use double quotes everywhere. The application code consistently uses lowercase as well. This database library using double quotes should thus not be a problem, should it?

Are you sure it’s not something else that’s wrong?

If you really need to fix this with a temporary workaround, instead of commenting out the calls to `quoteTableName` and using `$tableName[0]` instead of `$tableName`, you should rather comment out the two lines applying `quoteIdentifier` [here](https://github.com/delight-im/PHP-DB/blob/7a03da20b5592fa445c10cd6c7245d51037292c4/src/PdoDatabase.php#L430) and [here](https://github.com/delight-im/PHP-DB/blob/7a03da20b5592fa445c10cd6c7245d51037292c4/src/PdoDatabase.php#L435). That’s the solution requiring the fewest changes, and keeps the newly introduced schema qualifiers, which you asked for.

By the way, I also disagree with the article you linked to. Instead of “don’t use (double) quotes”, it should say “don’t use uppercase” (or “use both correctly”, of course).

**Comment by MB34** [comment]
> we don’t do the wrong `"schema.users_throttling"` but the correct `"schema"."users_throttling"`, as far as I can see...

You need to point out that to return the correct `"schema"."users_throttling"`, you need to pass the schema in the `$dbSchema` parameter and not the `$dbTablePrefix` parameter as I did and got this returned:
`"schema.users_throttling"`

After making that change, it all works, except that I cannot return the Id or Roles for the logged in user but that is a different issue.

Thx...

**Comment by ocram** [comment]
In issue https://github.com/delight-im/PHP-DB/issues/9, where we discussed the schema support, I wrote the following:

> Support for the database schema has also been added to our authentication library now, namely in the form of **another** [emphasis added] argument to the constructor

And in the README of the [authentication library](https://github.com/delight-im/PHP-Auth), it says:

> If all your database tables need a common database name, schema name, or other qualifier that must be specified explicitly, you can optionally pass that qualifier to the constructor as the sixth parameter, which is named `$dbSchema`.

Anyway, I’m really glad this has just been the result of miscommunication. Happy to know that the schema support is working as expected.

Really appreciate your feedback! Please rather open a new issue than not when in doubt.

Regarding your final comment:

> except that I cannot return the Id or Roles for the logged in user

Let’s definitely talk about this in the issue tracker for the authentication library.

**Comment by MB34** [comment]
Yeah, I  posted the Auth issue already.
