### ISSUE TITLE
Count of retrieved rows and selecting 1 entry

### ISSUE THREAD

**Issue by nssnl** [delight-im/PHP-DB#22]
First of all great library. Nice clean way for my DB queries.
I'm in the progress of migrating all my DB queries to this library (coming from a library that is no longer maintained, and which provides a lot less 'clean' solution). 

As the previous library had some helper classes, just to be sure, I have these two questions:
- What would you suggest of being the best way to check if the SELECT query results and rows and the number of rows? I'm using `count()` on the returned array now (with some alterations as count() returns an error in some cases). Just wondering whether that's the recommended way. Sometimes I just want to check whether there are any results (perhaps could do `isset($result[0])` as well), in other cases I'd like to know the number of results.
- When limiting the SELECT query to 1 entry (LIMIT 1), the result is a multidimensonal array `Array ( [0] => Array (`, which is fine of course. I'll just 'flatten' it with `$result = $result[0];` for example. But just wondering that there is no option for a flattened array right away in case of querying one result.

Thanks!!

**Comment by ocram** [comment]
Thanks!

If you want to count the selectable rows without actually fetching them from the server, depending on your specific database system, there may be query types such as `SELECT * FROM ...` that you can use with `selectValue`.

If you really need the data anyway, and thus have to fetch it, using PHP’s `count` is fine – or really just checking if the entry at index zero is there if you need that.

As for your second problem, instead of using `select` for every query where you don’t need multi-dimensional results, have you tried using `selectRow`, or even just `selectValue`, or sometimes also `selectColumn`?

**Comment by nssnl** [comment]
Thanks for the response.
`selectRow` is what I was looking for. I was a bit confused by `LIMIT 0,1` in the example, as it seemed to imply to me that `selectRow` could return more then one row, but it makes sense. Thanks a lot!
