### ISSUE TITLE
 send of 75 bytes failed with errno=32 Broken pipe

### ISSUE THREAD

**Issue by Moniiiiii** [delight-im/PHP-DB#5]
```
 PDO::prepare(): send of 75 bytes failed with errno=32 Broken pipe in /home/manage/public_html/vendor/delight-im/db/src/PdoDatabase.php on line 561, Variables:Array
(
    [callback] => Closure Object
        (
            [this] => Delight\Db\PdoDatabase Object
                (
                    [previousAttributes:Delight\Db\PdoDatabase:private] => 
                    [attributes:Delight\Db\PdoDatabase:private] => 
                    [pdo:Delight\Db\PdoDatabase:private] => PDO Object
                        (
                        )

                    [dsn:Delight\Db\PdoDatabase:private] => 
                    [driverName:Delight\Db\PdoDatabase:private] => mysql
                    [profiler:Delight\Db\PdoDatabase:private] => 
                    [onConnectListeners:Delight\Db\PdoDatabase:private] => Array
                        (
                        )

                )

            [parameter] => Array
                (
                    [$stmt] => <required>
                )

        )

    [query] => SELECT ID FROM usersTable WHERE ID = 2
    [bindValues] => 
)

After a while of using your library, i'm just getting this error sometimes.

**Comment by ocram** [comment]
Thanks a lot for reporting this!

How are you creating the database connection? Are you passing a `PdoDataSource`, `PdoDsn` or `\PDO` instance to the constructor?

If you’re passing a `\PDO` instance, did you enable persistent connections there?

Might the problem be related to this PHP issue? https://bugs.php.net/bug.php?id=53287 There, it is suggested to change the [`wait_timeout`](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_wait_timeout) directive in the MySQL configuration.

Anyway, I guess the actual problem is actually lower in your stack (e.g. MySQL, PDO, your server) and not in this library.

**Comment by Moniiiiii** [comment]
I'm creating it just like that: 
```

        $dataSource = new \Delight\Db\PdoDataSource('mysql');
        $dataSource->setHostname($sql_host);
        $dataSource->setPort(3306);
        $dataSource->setDatabaseName($sql_db_name);
        $dataSource->setCharset('utf8mb4');
        $dataSource->setUsername($sql_user);
        $dataSource->setPassword($sql_pass);

        $connection = \Delight\Db\PdoDatabase::fromDataSource($dataSource);
```
Perhaps the persistent loop that I've occurs that? 

```

while(true){

    $addresses = $connection->select('SELECT ID FROM usersTable WHERE ID = 2');

   .....

   sleep(2)

}
```

Can you suggest any other way to loop over some data?

**Comment by ocram** [comment]
That looks pretty good, actually. So I’d say the error is unlikely to be in your application code, and equally unlikely to be in this library, because it doesn’t do such low-level stuff.

Thus the problem is probably due to a wrong configuration (e.g. of MySQL) or due to a bug in MySQL, PHP or your server (e.g. Apache or nginx).

Nevertheless, there are a few things you could do:

 1. How long is that loop actually running (before the error occurs)? Could you measure this, e.g. using `\time()` or `\microtime(true)`?
 1. What are the values for `connect_timeout`, `interactive_timeout`, `max_statement_time` or `max_execution_time`, `net_read_timeout`, `net_write_timeout`, `wait_timeout`, `query_cache_type`, `query_cache_size` and `read_buffer_size` in your MySQL configuration? Try executing the SQL statement `SHOW VARIABLES` or run `mysqld --verbose --help` in a terminal to see the current value.
 1. In PHP, there are two MySQL drivers for PDO (and thus for this library here): The old MySQL Client Library (`libmysqlclient`) and the new MySQL Native Driver (`mysqlnd`). Running

    ```php
    \var_dump($connection->getClientVersion());
    ```

    should output the name of the driver that you’re using. It’s probably the newer one, which has been the default in PHP for some time now. You could try the other driver and see if the problem occurs with there as well. How to switch between the two drivers depends on your platform and where you installed PHP from.
 1. Where’s your database located? On `localhost` or on a remote server?
 1. Is there any chance that MySQL might be going away while your application is running? Try looking into your MySQL error log, PHP error log, Apache/nginx error log.
 1. Try creating a new connection in every iteration of the loop. At least, try re-connecting whenever you catch that error, if it can be caught.

**Comment by Moniiiiii** [comment]
Thanks a bunch for your help, Actually that error happened once after a very long time lopping. I decided to use bash script to loop instead of while statement. 

`while true; do    php myfile.php;    sleep 2; done`

what do you think? thanks for taking time helping me even though the problem is not with your library.  appreciated <3

**Comment by ocram** [comment]
That looks better, since PHP was not really designed for running a single script for hours and keeping a connection to MySQL open all the time. With the Bash script, PHP responds to short requests frequently, which is exactly what it was designed for.

If the work you do before and after the loop is not too expensive, and thus having to do that work again every few seconds is fine, this solution is perfect.

If you want to steer a middle course, just let the loop run for an hour and start the PHP script from Bash about once per hour.
